apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
  labels:
    app: backend
spec:
  selector:
    app: backend
  type: {{ .Values.backend.service.type }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
