apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Values.namespace }}
  labels:
    app: db
spec:
  selector:
    app: db
  type: {{ .Values.db.service.type }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
