apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  type: {{ .Values.frontend.service.type }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
