namespace: exercise-8

image:
  repository: nginx
  tag: "1.29.6"
  pullPolicy: IfNotPresent

frontend:
  replicas: 1
  service:
    type: NodePort

backend:
  replicas: 1
  service:
    type: ClusterIP

db:
  replicas: 1
  service:
    type: ClusterIP

networkPolicy:
  enabled: true
